# ------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if
#     the code is regenerated.
# </auto-generated>
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# ------------------------------------------------------------------------------

from .base_numbers import BaseNumbers
# pylint: disable=line-too-long


class HungarianNumeric:
    LangMarker = 'Hun'
    CompoundNumberLanguage = False
    MultiDecimalSeparatorCulture = False
    NonStandardSeparatorVariants = []
    RoundNumberIntegerRegex = f'(?:száz|ezer|millió|milliárd|billió|trilliárd|trillió)'
    ZeroToNineIntegerRegex = f'(?:nulla|egy|kettő|két|három|négy|öt|hat|hét|nyolc|kilenc)'
    TwoToNineIntegerRegex = f'(?:kettő|két|három|négy|öt|hat|hét|nyolc|kilenc)'
    NegativeNumberTermsRegex = f'(?<negTerm>(mínusz|negatív)\\s+)'
    NegativeNumberSignRegex = f'^{NegativeNumberTermsRegex}.*'
    AnIntRegex = f'(egy)(?=\\s)'
    TenToNineteenIntegerRegex = f'(?:tizen(egy|kettő|két|három|négy|öt|hat|hét|nyolc|kilenc)|tíz)'
    TensNumberIntegerRegex = f'(?:kilencven|nyolcvan|hetven|hatvan|ötven|negyven|harminc|húsz)'
    SeparaIntRegex = f'(?:(({TenToNineteenIntegerRegex}|({TensNumberIntegerRegex}(\\s+)?{ZeroToNineIntegerRegex})|{TensNumberIntegerRegex}|{ZeroToNineIntegerRegex})(\\s+{RoundNumberIntegerRegex})*))|(({AnIntRegex}(\\s+{RoundNumberIntegerRegex})+))'
    AllIntRegex = f'(?:((({TenToNineteenIntegerRegex}|({TensNumberIntegerRegex}(\\s+)?{ZeroToNineIntegerRegex})|{TensNumberIntegerRegex}|{ZeroToNineIntegerRegex}|{AnIntRegex})(\\s+{RoundNumberIntegerRegex})+)\\s+(és\\s+)?)*{SeparaIntRegex})'
    PlaceHolderPureNumber = f'\\b'
    PlaceHolderDefault = f'(?=\\D)|\\b'
    PlaceHolderMixed = f'\\D|\\b'

    def NumbersWithPlaceHolder(placeholder):
        return f'(((?<!(\\d+(\\s*(K|k|M|G|T|B|b))?\\s*|\\p{{L}}))-\\s*)|(?<={placeholder}))\\d+(?!([\\.,]\\d+[a-zA-Z]))(?={placeholder})'
    NumbersWithSuffix = f'(((?<!\\d+(\\s*{BaseNumbers.NumberMultiplierRegex})?\\s*)-\\s*)|(?<=\\b))\\d+\\s*{BaseNumbers.NumberMultiplierRegex}(?=\\b)'
    RoundNumberIntegerRegexWithLocks = f'(?<=\\b)\\d+\\s+{RoundNumberIntegerRegex}(?=\\b)'
    NumbersWithDozenSuffix = f'(((?<!\\d+(\\s*{BaseNumbers.NumberMultiplierRegex})?\\s*)-\\s*)|(?<=\\b))\\d+\\s+(tucat)(?=\\b)'
    AllIntRegexWithLocks = f'((?<=\\b){AllIntRegex}(?=\\b))'
    AllIntRegexWithDozenSuffixLocks = f'(?<=\\b)(((fél\\s+)?egy\\s+tucat)|({AllIntRegex}\\s+(tucat)))(?=\\b)'
    RoundNumberOrdinalRegex = f'(?:századik|ezredik|milliomodik|milliárdodik|billiomodik|trilliárdodik|trilliomodik)'
    NumberOrdinalRegex = f'(?:első|második|harmadik|negyedik|ötödik|hatodik|hetedik|nyolcadik|kilencedik|tizedik|tizenegyedik|tizenkettedik|tizenharmadik|tizennegyedik|tizenötödik|tizenhatodik|tizenhetedik|tizennyolcadik|tizenkilencedik|huszadik|harmincadik|negyvenedik|ötvenedik|hatvanadik|hetvenedik|nyolcvanadik|kilencvenedik)'
    RelativeOrdinalRegex = f'(?<relativeOrdinal>(következő|előző|jelenlegi|utolsó|utolsó\\s+előtti|utolsó\\s+előtti\\s+egy|utolsó\\s+előtti\\s+kettő))'
    SuffixBasicOrdinalRegex = f'(?:(((({TensNumberIntegerRegex}(\\s+)?{ZeroToNineIntegerRegex})|{TensNumberIntegerRegex}|{ZeroToNineIntegerRegex}|{AnIntRegex})(\\s+{RoundNumberIntegerRegex})+)\\s+(és\\s+)?)*({TensNumberIntegerRegex}(\\s+|\\s*-\\s*))?{NumberOrdinalRegex})'
    SuffixRoundNumberOrdinalRegex = f'(?:({AllIntRegex}\\s+){RoundNumberOrdinalRegex})'
    AllOrdinalNumberRegex = f'(?:{SuffixBasicOrdinalRegex}|{SuffixRoundNumberOrdinalRegex})'
    AllOrdinalRegex = f'(?:{AllOrdinalNumberRegex}|{RelativeOrdinalRegex})'
    OrdinalSuffixRegex = f'(?<=\\b)(?:(\\d*(1\\.)|(\d*(2|3)\\.))|\d*\\.?)(?=\\b)'
    OrdinalNumericRegex = f'(?<=\\b)(?:\\d{{1,3}}(\\s*,\\s*\\d{{3}})*\\s*\\.)(?=\\b)'
    OrdinalRoundNumberRegex = f'(?<!egy\\s+){RoundNumberOrdinalRegex}'
    OrdinalHungarianRegex = f'(?<=\\b){AllOrdinalRegex}(?=\\b)'
    FractionNotationWithSpacesRegex = f'(((?<=\\W|^)-\\s*)|(?<=\\b))\\d+\\s+\\d+[/]\\d+(?=(\\b[^/]|$))'
    FractionNotationRegex = f'{BaseNumbers.FractionNotationRegex}'
    FractionMultiplierRegex = f'(?<fracMultiplier>\\s+és\\s+(egy|{TwoToNineIntegerRegex})\\s+(fél|negyed|harmad|negyed|ötöd|hatod|heted|nyolcad|kilenced|tized))'
    RoundMultiplierWithFraction = f'(?<=(?<!{RoundNumberIntegerRegex}){FractionMultiplierRegex}\\s+)?(?<multiplier>(?:millió|milliárd|billió|trilliárd|trillió))(?={FractionMultiplierRegex}?$)'
    RoundMultiplierRegex = f'\\b\\s*((of\\s+)?egy\\s+)?({RoundMultiplierWithFraction}|(?<multiplier>(?:száz|ezer)$))'
    FractionNounRegex = f'(?<=\\b)({AllIntRegex}\\s+(és\\s+)?)?(({AllIntRegex})(\\s+|\\s*-\\s*)((({AllOrdinalNumberRegex})|({RoundNumberOrdinalRegex}))s|fél|negyed)((\\s+of\\s+a)?\\s+{RoundNumberIntegerRegex})?|(fél(\\s+a)?|negyed(\\s+of\\s+a)?)\\s+{RoundNumberIntegerRegex})(?=\\b)'
    FractionNounWithArticleRegex = f'(?<=\\b)(((({AllIntRegex}|{RoundNumberIntegerRegexWithLocks})\\s+(és\\s+)?)?(egy)(\\s+|\\s*-\\s*)(?!\\belső\\b|\\bmásodik\\b)(({AllOrdinalNumberRegex})|({RoundNumberOrdinalRegex})|(fél|negyed)(((\\s+of)?\\s+egy)?\\s+{RoundNumberIntegerRegex})?))|(fél))(?=\\b)'
    FractionPrepositionRegex = f'(?<!{BaseNumbers.CommonCurrencySymbol}\\s*)(?<=\\b)(?<numerator>({AllIntRegex})|((?<![\\.,])\\d+))\\s+(per|(?<ambiguousSeparator>in|out\\s+of))\\s+(?<denominator>({AllIntRegex})|(\\d+)(?![\\.,]))(?=\\b)'
    FractionPrepositionWithinPercentModeRegex = f'(?<!{BaseNumbers.CommonCurrencySymbol}\\s*)(?<=\\b)(?<numerator>({AllIntRegex})|((?<![\\.,])\\d+))\\s+per\\s+(?<denominator>({AllIntRegex})|(\\d+)(?![\\.,]))(?=\\b)'
    AllPointRegex = f'((\\s+{ZeroToNineIntegerRegex})+|(\\s+{SeparaIntRegex}))'
    AllFloatRegex = f'{AllIntRegex}(\\s+egész){AllPointRegex}'
    DoubleWithMultiplierRegex = f'(((?<!\\d+(\\s*{BaseNumbers.NumberMultiplierRegex})?\\s*)-\\s*)|((?<=\\b)(?<!\\d+[\\.,])))((\d{{1,3}}(,\d{{3}})+(\\.\\d+)?)|(\d+[\\.,]\\d+))\\s*{BaseNumbers.NumberMultiplierRegex}(?=\\b)'
    DoubleExponentialNotationRegex = f'(((?<!\\d+(\\s*{BaseNumbers.NumberMultiplierRegex})?\\s*)-\\s*)|((?<=\\b)(?<!\\d+[\\.,])))(\\d+([\\.,]\\d+)?)(e|x10\\^)([+-]*[1-9]\\d*)(?=\\b)'
    DoubleCaretExponentialNotationRegex = f'(((?<!\\d+(\\s*{BaseNumbers.NumberMultiplierRegex})?\\s*)-\\s*)|((?<=\\b)(?<!\\d+[\\.,])))(\\d+([\\.,]\\d+)?)\\^([+-]*[1-9]\\d*)(?=\\b)'

    def DoubleDecimalPointRegex(placeholder):
        return f'(((?<!(\d+(\s*(K|k|M|G|T|B|b))?\s*|\p{{L}}))-\s*)|((?<={placeholder})(?<!\d+[\.,])))(\d{{1,3}}(,\d{{3}})+(\.\d+)?|\d+[\.,]\d+)(?!([\.,]\d+))(?={placeholder})'

    def DoubleWithoutIntegralRegex(placeholder):
        return f'(?<=\s|^)(?<!(\d+))[\.,]\d+(?!([\.,]\d+))(?={placeholder})'
    DoubleWithRoundNumber = f'(((?<!\\d+(\\s*{BaseNumbers.NumberMultiplierRegex})?\\s*)-\\s*)|((?<=\\b)(?<!\\d+[\\.,])))(\\d{{1,3}}(,\\d{{3}})+(\\.\\d+)?|\\d+[\\.,]\\d+)\\s+{RoundNumberIntegerRegex}(?=\\b)'
    DoubleAllFloatRegex = f'((?<=\\b){AllFloatRegex}(?=\\b))'
    ConnectorRegex = f'(?<spacer>és)'
    NumberWithSuffixPercentage = f'(?<!%({BaseNumbers.NumberReplaceToken})?)({BaseNumbers.NumberReplaceToken}(\\s*))?(%(?!{BaseNumbers.NumberReplaceToken})|(százalék)\\b)'
    FractionNumberWithSuffixPercentage = f'(({BaseNumbers.FractionNumberReplaceToken})\\s+of)'
    NumberWithPrefixPercentage = f'(százalék\\s+of)(\\s*)({BaseNumbers.NumberReplaceToken})'
    NumberWithPrepositionPercentage = f'({BaseNumbers.NumberReplaceToken})\\s*(in|out\\s+of)\\s*({BaseNumbers.NumberReplaceToken})'
    TillRegex = f'((?<!\\begyenlő\\s+)ig|keresztül|--|-|—|——|~|–)'
    MoreRegex = f'(?:(nagyobb|több|magasabb|nagyobb)(\\s+mint)?|fölött|túl|meghalad(ja|va)|túlhalad(ja|va)|(?<!<|=)>)'
    LessRegex = f'(?:(kevesebb|alacsonyabb|kisebb)(\\s+mint)?|alatt|(?<!>|=)<)'
    EqualRegex = f'(egyenlő(\\s+(vele|mint))?|(?<!<|>)=)'
    MoreOrEqualPrefix = f'((nem\\s+{LessRegex})|(legalább))'
    MoreOrEqual = f'(?:({MoreRegex}\\s+(vagy)?\\s+{EqualRegex})|({EqualRegex}\\s+(vagy)?\\s+{MoreRegex})|{MoreOrEqualPrefix}(\\s+(vagy)?\\s+{EqualRegex})?|({EqualRegex}\\s+(vagy)?\\s+)?{MoreOrEqualPrefix}|>\\s*=|≥)'
    MoreOrEqualSuffix = f'((és|vagy)\\s+(((több|nagyobb|magasabb|nagyobb)((?!\\s+mint)|(\\s+mint(?!((\\s+vagy\\s+egyenlő\\s+vele)?\\s*\\d+)))))|((fölött|túl)(?!\\s+mint))))'
    LessOrEqualPrefix = f'((nem\\s+{MoreRegex})|(legfeljebb)|(maximum))'
    LessOrEqual = f'(({LessRegex}\\s+(vagy)?\\s+{EqualRegex})|({EqualRegex}\\s+(vagy)?\\s+{LessRegex})|{LessOrEqualPrefix}(\\s+(vagy)?\\s+{EqualRegex})?|({EqualRegex}\\s+(vagy)?\\s+)?{LessOrEqualPrefix}|<\\s*=|≤)'
    LessOrEqualSuffix = f'((és|vagy)\\s+(kevesebb|alacsonyabb|kisebb)((?!\\s+mint)|(\\s+mint(?!(\\s*\\d+)))))'
    NumberSplitMark = f'(?![,.](?!\\d+))(?!\\s*\\b(és\\s+({LessRegex}|{MoreRegex})|de|vagy|ig)\\b)'
    MoreRegexNoNumberSucceed = f'((nagyobb|több|magasabb|nagyobb)((?!\\s+mint)|\\s+(mint(?!(\\s*\\d+))))|(fölött|túl)(?!(\\s*\\d+)))'
    LessRegexNoNumberSucceed = f'((kevesebb|alacsonyabb|kisebb)((?!\\s+mint)|\\s+(mint(?!(\\s*\\d+))))|(alatt)(?!(\\s*\\d+)))'
    EqualRegexNoNumberSucceed = f'(egyenlő((?!\\s+(vele|mint))|(\\s+(vele|mint)(?!(\\s*\\d+)))))'
    OneNumberRangeMoreRegex1 = f'({MoreOrEqual}|{MoreRegex})\\s*(a\\s+)?(?<number1>({NumberSplitMark}.)+)'
    OneNumberRangeMoreRegex1LB = f'(?<!nem\\s+){OneNumberRangeMoreRegex1}'
    OneNumberRangeMoreRegex2 = f'(?<number1>({NumberSplitMark}.)+)\\s*{MoreOrEqualSuffix}'
    OneNumberRangeMoreSeparateRegex = f'({EqualRegex}\\s+(?<number1>({NumberSplitMark}.)+)(\\s+vagy\\s+){MoreRegexNoNumberSucceed})|({MoreRegex}\\s+(?<number1>({NumberSplitMark}.)+)(\\s+vagy\\s+){EqualRegexNoNumberSucceed})'
    OneNumberRangeLessRegex1 = f'({LessOrEqual}|{LessRegex})\\s*(a\\s+)?(?<number2>({NumberSplitMark}.)+)'
    OneNumberRangeLessRegex1LB = f'(?<!nem\\s+){OneNumberRangeLessRegex1}'
    OneNumberRangeLessRegex2 = f'(?<number2>({NumberSplitMark}.)+)\\s*{LessOrEqualSuffix}'
    OneNumberRangeLessSeparateRegex = f'({EqualRegex}\\s+(?<number1>({NumberSplitMark}.)+)(\\s+vagy\\s+){LessRegexNoNumberSucceed})|({LessRegex}\\s+(?<number1>({NumberSplitMark}.)+)(\\s+vagy\\s+){EqualRegexNoNumberSucceed})'
    OneNumberRangeEqualRegex = f'(?<!\\bmint\\s+vagy\\s+){EqualRegex}\\s*(a\\s+)?(?<number1>({NumberSplitMark}.)+)'
    TwoNumberRangeRegex1 = f'között\\s*(a\\s+)?(?<number1>({NumberSplitMark}.)+)\\s*és\\s*(a\\s+)?(?<number2>({NumberSplitMark}.)+)'
    TwoNumberRangeRegex2 = f'({OneNumberRangeMoreRegex1}|{OneNumberRangeMoreRegex2})\\s*(és|de|,)\\s*({OneNumberRangeLessRegex1}|{OneNumberRangeLessRegex2})'
    TwoNumberRangeRegex3 = f'({OneNumberRangeLessRegex1}|{OneNumberRangeLessRegex2})\\s*(és|de|,)\\s*({OneNumberRangeMoreRegex1}|{OneNumberRangeMoreRegex2})'
    TwoNumberRangeRegex4 = f'(from\\s+)?(?<number1>({NumberSplitMark}(?!\\bfrom\\b).)+)\\s*{TillRegex}\\s*(a\\s+)?(?<number2>({NumberSplitMark}.)+)'
    AmbiguousFractionConnectorsRegex = f'(\\bin\\b)'
    DecimalSeparatorChar = ','
    FractionMarkerToken = 'per'
    NonDecimalSeparatorChar = '.'
    HalfADozenText = 'hat'
    WordSeparatorToken = 'és'
    WrittenDecimalSeparatorTexts = ['egész']
    WrittenGroupSeparatorTexts = ['pont']
    WrittenIntegerSeparatorTexts = ['és']
    WrittenFractionSeparatorTexts = ['és']
    HalfADozenRegex = f'fél\\s+tucat'
    DigitalNumberRegex = f'((?<=\\b)(száz|ezer|millió|milliárd|billió|trilliárd|trillió|tucat)(?=\\b))|((?<=(\\d|\\b)){BaseNumbers.MultiplierLookupRegex}(?=\\b))'
    CardinalNumberMap = dict([
        ('nulla', 0),
        ('egy', 1),
        ('kettő', 2),
        ('két', 2),
        ('három', 3),
        ('négy', 4),
        ('öt', 5),
        ('hat', 6),
        ('hét', 7),
        ('nyolc', 8),
        ('kilenc', 9),
        ('tíz', 10),
        ('tizenegy', 11),
        ('tizenkettő', 12),
        ('tizenkét', 12),
        ('tucat', 12),
        ('tizenhárom', 13),
        ('tizennégy', 14),
        ('tizenöt', 15),
        ('tizenhat', 16),
        ('tizenhét', 17),
        ('tizennyolc', 18),
        ('tizenkilenc', 19),
        ('húsz', 20),
        ('harminc', 30),
        ('negyven', 40),
        ('ötven', 50),
        ('hatvan', 60),
        ('hetven', 70),
        ('nyolcvan', 80),
        ('kilencven', 90),
        ('száz', 100),
        ('ezer', 1000),
        ('millió', 1000000),
        ('milliárd', 1000000000),
        ('billió', 1000000000000),
        ('trilliárd', 1000000000000000),
        ('trillió', 1000000000000000000)
    ])
    OrdinalNumberMap = dict([
        ('első', 1),
        ('második', 2),
        ('fél', 2),
        ('harmadik', 3),
        ('negyedik', 4),
        ('negyed', 4),
        ('ötödik', 5),
        ('hatodik', 6),
        ('hetedik', 7),
        ('nyolcadik', 8),
        ('kilencedik', 9),
        ('tizedik', 10),
        ('tizenegyedik', 11),
        ('tizenkettedik', 12),
        ('tizenharmadik', 13),
        ('tizennegyedik', 14),
        ('tizenötödik', 15),
        ('tizenhatodik', 16),
        ('tizenhetedik', 17),
        ('tizennyolcadik', 18),
        ('tizenkilencedik', 19),
        ('huszadik', 20),
        ('harmincadik', 30),
        ('negyvenedik', 40),
        ('ötvenedik', 50),
        ('hatvanadik', 60),
        ('hetvenedik', 70),
        ('nyolcvanadik', 80),
        ('kilencvenedik', 90),
        ('századik', 100),
        ('ezredik', 1000),
        ('milliomodik', 1000000),
        ('milliárdodik', 1000000000),
        ('billiomodik', 1000000000000),
        ('trilliárdodik', 1000000000000000),
        ('trilliomodik', 1000000000000000000)
    ])
    RoundNumberMap = dict([
        ('száz', 100),
        ('ezer', 1000),
        ('millió', 1000000),
        ('milliárd', 1000000000),
        ('billió', 1000000000000),
        ('trilliárd', 1000000000000000),
        ('trillió', 1000000000000000000),
        ('századik', 100),
        ('ezredik', 1000),
        ('milliomodik', 1000000),
        ('milliárdodik', 1000000000),
        ('billiomodik', 1000000000000),
        ('trilliárdodik', 1000000000000000),
        ('trilliomodik', 1000000000000000000),
        ('tucat', 12),
        ('k', 1000),
        ('m', 1000000),
        ('g', 1000000000),
        ('b', 1000000000),
        ('t', 1000000000000)
    ])
    AmbiguityFiltersDict = dict([
        ('\\begy\\b', '\\b(a|az|ez|ezt|azt)\\s+(egy)\\b')
    ])
    RelativeReferenceOffsetMap = dict([
        ('utolsó', '0'),
        ('következő', '1'),
        ('jelenlegi', '0'),
        ('előző', '-1'),
        ('utolsó előtti', '-1'),
        ('utolsó előtti egy', '-1'),
        ('utolsó előtti kettő', '-2')
    ])
    RelativeReferenceRelativeToMap = dict([
        ('utolsó', 'end'),
        ('következő', 'current'),
        ('jelenlegi', 'current'),
        ('előző', 'current'),
        ('utolsó előtti', 'end'),
        ('utolsó előtti egy', 'end'),
        ('utolsó előtti kettő', 'end')
    ])